### ISSUE TITLE
Switch to JLD2

### ISSUE THREAD

**Issue by devmotion** [JuliaDiffEq/DiffEqProblemLibrary.jl#10]
Lately it was difficult to test `DelayDiffEq` on Windows 32bit, since we often got HDF5 build errors (see https://github.com/JuliaDiffEq/DelayDiffEq.jl/pull/17#issuecomment-318907774). At least for DelayDiffEq, the dependency on HDF5 originates from DiffEqProblemLibrary, and in particular from its requirement JLD. Maybe it would be a good idea to switch to [JLD2](https://github.com/simonster/JLD2.jl) which does not depend on the HDF5 C library?

**Comment by ChrisRackauckas** [comment]
I like this idea. Or I think we can just get rid of the load functions and keep the JLD files, and change 

https://github.com/JuliaDiffEq/DiffEqPDEBase.jl/blob/master/test/mesh_examples_tests.jl

to directly load the `.jld`s. I just don't think the load functions are necessary anymore.

**Comment by ChrisRackauckas** [comment]
I just did those changes and will close this when the tests pass.

**Comment by ChrisRackauckas** [comment]
Tests passed and releasing. Thanks for bringing this up.
